site_name: 'Kimi Brain'
docs_dir: 'Wiki'
strict: false
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - toc.integrate
plugins:
  - search
  - tags
  - roamlinks
  - git-revision-date-localized
  - macros
markdown_extensions:
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
